services:
  # app:
  #   container_name: board_app
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure
  #   volumes:
  #     - api:/usr/src/app/
  #   depends_on:
  #     - board-postgres          # Uncomment this when using postgres.


  fund-postgres:
    image: postgres:latest
    container_name: fund_db_postgres
    environment:
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

  migrate:
    environment:
        - PG_USER=${PG_USER}
        - PG_PASS=${PG_PASS}
        - PG_DB=${PG_DB}
    image: migrate/migrate
    volumes:
      - ./pg/migrations:/migrations
    command: [ "-path", "migrations", "-database",  "postgres://${PG_USER}:${PG_PASS}@fund-postgres:5432/${PG_DB}?sslmode=disable", "up" ]
    links:
      - fund-postgres
    depends_on:
      - fund-postgres


volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.