// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fundevents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFundEvents = `-- name: GetFundEvents :many
SELECT fund_event.id, fund_event.fund_id, fund_event.kind, fund_event.occurred_at, fund_event.actor_member_id, fund_event.subject_member_id, fund_event.amount_cents, fund_event.detail, fund_event.reference_id, fund_event.created,
       actor.bco_name   AS actor_name,
       subject.bco_name AS subject_name
FROM fund_event
         LEFT JOIN member actor ON actor.id = fund_event.actor_member_id
         LEFT JOIN member subject ON subject.id = fund_event.subject_member_id
WHERE fund_event.fund_id = $1
ORDER BY fund_event.occurred_at DESC, fund_event.created DESC
LIMIT $2
`

type GetFundEventsParams struct {
	FundID uuid.UUID
	Limit  int32
}

type GetFundEventsRow struct {
	FundEvent   FundEvent
	ActorName   pgtype.Text
	SubjectName pgtype.Text
}

// Newest first, with the actor's and subject's names resolved so the feed does
// not have to issue a query per row.
func (q *Queries) GetFundEvents(ctx context.Context, arg GetFundEventsParams) ([]GetFundEventsRow, error) {
	rows, err := q.db.Query(ctx, getFundEvents, arg.FundID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundEventsRow
	for rows.Next() {
		var i GetFundEventsRow
		if err := rows.Scan(
			&i.FundEvent.ID,
			&i.FundEvent.FundID,
			&i.FundEvent.Kind,
			&i.FundEvent.OccurredAt,
			&i.FundEvent.ActorMemberID,
			&i.FundEvent.SubjectMemberID,
			&i.FundEvent.AmountCents,
			&i.FundEvent.Detail,
			&i.FundEvent.ReferenceID,
			&i.FundEvent.Created,
			&i.ActorName,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFundEvent = `-- name: InsertFundEvent :one
INSERT INTO fund_event (id, fund_id, kind, occurred_at, actor_member_id, subject_member_id,
                        amount_cents, detail, reference_id)
VALUES ($1, $2, $3, COALESCE($9::timestamptz, now()), $4, $5, $6, $7, $8)
RETURNING id, fund_id, kind, occurred_at, actor_member_id, subject_member_id, amount_cents, detail, reference_id, created
`

type InsertFundEventParams struct {
	ID              uuid.UUID
	FundID          uuid.UUID
	Kind            FundEventKind
	ActorMemberID   uuid.NullUUID
	SubjectMemberID uuid.NullUUID
	AmountCents     pgtype.Int4
	Detail          pgtype.Text
	ReferenceID     uuid.NullUUID
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertFundEvent(ctx context.Context, arg InsertFundEventParams) (FundEvent, error) {
	row := q.db.QueryRow(ctx, insertFundEvent,
		arg.ID,
		arg.FundID,
		arg.Kind,
		arg.ActorMemberID,
		arg.SubjectMemberID,
		arg.AmountCents,
		arg.Detail,
		arg.ReferenceID,
		arg.OccurredAt,
	)
	var i FundEvent
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.OccurredAt,
		&i.ActorMemberID,
		&i.SubjectMemberID,
		&i.AmountCents,
		&i.Detail,
		&i.ReferenceID,
		&i.Created,
	)
	return i, err
}
