// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceFundNextPayment = `-- name: AdvanceFundNextPayment :one
UPDATE fund
SET next_payment = CASE
                       WHEN payout_frequency = 'once' THEN NULL
                       WHEN payout_frequency = 'daily' THEN next_payment + (interval '1 day' * (SELECT MIN(n)
                                                                                                FROM generate_series(1, 3650) n
                                                                                                WHERE next_payment + (interval '1 day' * n) > now()))
                       ELSE next_payment + (interval '1 month' * (SELECT MIN(n)
                                                                  FROM generate_series(1, 60) n
                                                                  WHERE next_payment + (interval '1 month' * n) > now()))
    END,
    updated      = now()
WHERE id = $1
RETURNING id, name, description, provider_id, provider_name, goal_cents, payout_frequency, active, principal, expires, next_payment, created, updated
`

// Moves the fund to its next scheduled payout, anchored on the existing date
// rather than stepped one month at a time: adding a month repeatedly walks the
// 31st to the 28th and then leaves it there, so a fund that paid on the 31st
// would quietly become a fund that pays on the 28th.
//
// Multiplying the original date instead means February clamps for February only.
// generate_series bounds the search at 60 months, which is only reachable if the
// planner has not run in five years.
//
// A 'once' fund gets NULL: it has paid, and there is no next time.
//
// 'daily' steps by days on the same anchored principle. It needs no clamping --
// every month has a tomorrow -- but it does need a wider search, since 60 of
// anything is two months of days. Ten years of them keeps the bound honest
// against a test fund left running.
func (q *Queries) AdvanceFundNextPayment(ctx context.Context, id uuid.UUID) (Fund, error) {
	row := q.db.QueryRow(ctx, advanceFundNextPayment, id)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderID,
		&i.ProviderName,
		&i.GoalCents,
		&i.PayoutFrequency,
		&i.Active,
		&i.Principal,
		&i.Expires,
		&i.NextPayment,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const approveBatchPayout = `-- name: ApproveBatchPayout :one
UPDATE batch_payout
SET status      = 'ready',
    approved_by = $2,
    approved_at = now(),
    updated     = now()
WHERE id = $1
  AND status = 'awaiting_approval'
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

type ApproveBatchPayoutParams struct {
	ID         uuid.UUID
	ApprovedBy uuid.NullUUID
}

// Approves only from 'awaiting_approval'. The status predicate makes this a
// compare-and-set: a batch already cancelled by the expiry sweep, or already
// approved by another treasurer, returns no row rather than being overwritten.
func (q *Queries) ApproveBatchPayout(ctx context.Context, arg ApproveBatchPayoutParams) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, approveBatchPayout, arg.ID, arg.ApprovedBy)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const cancelExpiredBatchPayouts = `-- name: CancelExpiredBatchPayouts :many
UPDATE batch_payout
SET status         = 'cancelled',
    failure_reason = 'approval window expired',
    updated        = now()
WHERE status = 'awaiting_approval'
  AND approval_deadline IS NOT NULL
  AND approval_deadline <= now()
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

// Sweeps batches whose approval window closed. Bounded by status so an approved
// batch that has simply sat past its deadline is never cancelled out from under a
// submission that is already in flight.
func (q *Queries) CancelExpiredBatchPayouts(ctx context.Context) ([]BatchPayout, error) {
	rows, err := q.db.Query(ctx, cancelExpiredBatchPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchPayout
	for rows.Next() {
		var i BatchPayout
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AmountCents,
			&i.NumEnrollments,
			&i.Status,
			&i.FailureReason,
			&i.Notes,
			&i.Description,
			&i.ProviderBatchID,
			&i.PayoutDate,
			&i.Created,
			&i.Updated,
			&i.SenderBatchID,
			&i.ApprovalDeadline,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveEnrollmentsForPayout = `-- name: GetActiveEnrollmentsForPayout :many
SELECT fund_enrollment.id, fund_enrollment.fund_id, fund_enrollment.member_id, fund_enrollment.member_bco_name, fund_enrollment.first_payout_date, fund_enrollment.active, fund_enrollment.created, fund_enrollment.updated, fund_enrollment.paypal_email
FROM fund_enrollment
         JOIN member ON member.id = fund_enrollment.member_id
         JOIN fund ON fund.id = fund_enrollment.fund_id
WHERE fund_enrollment.fund_id = $1
  AND fund.active = true
  AND fund_enrollment.active = true
  AND member.active = true
  AND fund_enrollment.first_payout_date <= now()
ORDER BY fund_enrollment.created
`

// The fund's own active flag is checked here as well as by the service, because
// deactivating a fund stops donations but leaves enrollments alone -- so without
// it a closed fund still has payable enrollees and can still send money.
func (q *Queries) GetActiveEnrollmentsForPayout(ctx context.Context, fundID uuid.UUID) ([]FundEnrollment, error) {
	rows, err := q.db.Query(ctx, getActiveEnrollmentsForPayout, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FundEnrollment
	for rows.Next() {
		var i FundEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.MemberID,
			&i.MemberBcoName,
			&i.FirstPayoutDate,
			&i.Active,
			&i.Created,
			&i.Updated,
			&i.PaypalEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchPayoutById = `-- name: GetBatchPayoutById :one
SELECT id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
FROM batch_payout
WHERE id = $1
`

func (q *Queries) GetBatchPayoutById(ctx context.Context, id uuid.UUID) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, getBatchPayoutById, id)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const getBatchPayoutBySenderBatchId = `-- name: GetBatchPayoutBySenderBatchId :one
SELECT id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
FROM batch_payout
WHERE sender_batch_id = $1
`

func (q *Queries) GetBatchPayoutBySenderBatchId(ctx context.Context, senderBatchID uuid.UUID) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, getBatchPayoutBySenderBatchId, senderBatchID)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const getBatchPayoutsByFundId = `-- name: GetBatchPayoutsByFundId :many
SELECT id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
FROM batch_payout
WHERE fund_id = $1
ORDER BY payout_date DESC
`

func (q *Queries) GetBatchPayoutsByFundId(ctx context.Context, fundID uuid.UUID) ([]BatchPayout, error) {
	rows, err := q.db.Query(ctx, getBatchPayoutsByFundId, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchPayout
	for rows.Next() {
		var i BatchPayout
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AmountCents,
			&i.NumEnrollments,
			&i.Status,
			&i.FailureReason,
			&i.Notes,
			&i.Description,
			&i.ProviderBatchID,
			&i.PayoutDate,
			&i.Created,
			&i.Updated,
			&i.SenderBatchID,
			&i.ApprovalDeadline,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchPayoutsByStatus = `-- name: GetBatchPayoutsByStatus :many
SELECT id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
FROM batch_payout
WHERE status = $1
ORDER BY payout_date
`

func (q *Queries) GetBatchPayoutsByStatus(ctx context.Context, status PayoutStatus) ([]BatchPayout, error) {
	rows, err := q.db.Query(ctx, getBatchPayoutsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchPayout
	for rows.Next() {
		var i BatchPayout
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AmountCents,
			&i.NumEnrollments,
			&i.Status,
			&i.FailureReason,
			&i.Notes,
			&i.Description,
			&i.ProviderBatchID,
			&i.PayoutDate,
			&i.Created,
			&i.Updated,
			&i.SenderBatchID,
			&i.ApprovalDeadline,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchPayoutsNeedingReminder = `-- name: GetBatchPayoutsNeedingReminder :many
SELECT id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
FROM batch_payout
WHERE status = 'awaiting_approval'
  AND reminder_sent_at IS NULL
  AND approval_deadline IS NOT NULL
  AND approval_deadline <= now() + $1::interval
  AND approval_deadline > now()
ORDER BY approval_deadline
`

// Batches inside the reminder window that have not been reminded yet.
func (q *Queries) GetBatchPayoutsNeedingReminder(ctx context.Context, remindWithin pgtype.Interval) ([]BatchPayout, error) {
	rows, err := q.db.Query(ctx, getBatchPayoutsNeedingReminder, remindWithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchPayout
	for rows.Next() {
		var i BatchPayout
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AmountCents,
			&i.NumEnrollments,
			&i.Status,
			&i.FailureReason,
			&i.Notes,
			&i.Description,
			&i.ProviderBatchID,
			&i.PayoutDate,
			&i.Created,
			&i.Updated,
			&i.SenderBatchID,
			&i.ApprovalDeadline,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFundBalanceCents = `-- name: GetFundBalanceCents :one
SELECT (COALESCE((SELECT SUM(dp.amount_cents)
                  FROM donation
                           JOIN donation_payment dp ON donation.id = dp.donation_id
                  WHERE donation.fund_id = $1), 0)
    - COALESCE((SELECT SUM(payout.amount_cents)
                FROM payout
                         JOIN batch_payout ON batch_payout.id = payout.batch_id
                WHERE batch_payout.fund_id = $1
                  AND payout.status NOT IN ('failed', 'cancelled', 'returned')), 0))::bigint
           AS available_cents
`

// What the fund can actually pay out: everything donated, less everything already
// committed to a payout.
//
// Committed deliberately includes payouts that have not settled yet. Money sent
// but still 'pending' at the provider is gone as far as the next batch is
// concerned, and counting only 'paid' would let two batches in the same week
// promise the same cents twice.
//
// 'failed' and 'cancelled' never left, and 'returned' came back, so all three are
// available again.
// The cast wraps the whole subtraction: applied to each operand instead, sqlc
// reads the result as int32 and a fund holding more than about $21m silently
// fails to scan.
func (q *Queries) GetFundBalanceCents(ctx context.Context, fundID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFundBalanceCents, fundID)
	var available_cents int64
	err := row.Scan(&available_cents)
	return available_cents, err
}

const getFundsDueForPayout = `-- name: GetFundsDueForPayout :many
SELECT id, name, payout_frequency, next_payment
FROM fund
WHERE active = true
  AND next_payment IS NOT NULL
  AND next_payment <= now()
ORDER BY next_payment
`

type GetFundsDueForPayoutRow struct {
	ID              uuid.UUID
	Name            string
	PayoutFrequency PayoutFrequency
	NextPayment     DBTime
}

// The planner runs daily and asks "what is due today", so a fund whose date has
// passed is included rather than skipped: a missed run must still pay out, late,
// instead of silently dropping a period. 'once' funds are advanced to NULL after
// planning, which is what keeps them from being picked up forever.
func (q *Queries) GetFundsDueForPayout(ctx context.Context) ([]GetFundsDueForPayoutRow, error) {
	rows, err := q.db.Query(ctx, getFundsDueForPayout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundsDueForPayoutRow
	for rows.Next() {
		var i GetFundsDueForPayoutRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PayoutFrequency,
			&i.NextPayment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayoutsByBatchId = `-- name: GetPayoutsByBatchId :many
SELECT id, fund_enrollment_id, batch_id, amount_cents, status, failure_reason, notes, description, payout_date, created, updated, provider_payout_item_id, destination_email, provider_fee_cents
FROM payout
WHERE batch_id = $1
ORDER BY created
`

func (q *Queries) GetPayoutsByBatchId(ctx context.Context, batchID uuid.UUID) ([]Payout, error) {
	rows, err := q.db.Query(ctx, getPayoutsByBatchId, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.FundEnrollmentID,
			&i.BatchID,
			&i.AmountCents,
			&i.Status,
			&i.FailureReason,
			&i.Notes,
			&i.Description,
			&i.PayoutDate,
			&i.Created,
			&i.Updated,
			&i.ProviderPayoutItemID,
			&i.DestinationEmail,
			&i.ProviderFeeCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBatchPayout = `-- name: InsertBatchPayout :one
INSERT INTO batch_payout (id, fund_id, amount_cents, num_enrollments, status, description, notes,
                          payout_date, sender_batch_id, approval_deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

type InsertBatchPayoutParams struct {
	ID               uuid.UUID
	FundID           uuid.UUID
	AmountCents      int32
	NumEnrollments   int32
	Status           PayoutStatus
	Description      pgtype.Text
	Notes            pgtype.Text
	PayoutDate       pgtype.Timestamptz
	SenderBatchID    uuid.UUID
	ApprovalDeadline NullDBTime
}

func (q *Queries) InsertBatchPayout(ctx context.Context, arg InsertBatchPayoutParams) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, insertBatchPayout,
		arg.ID,
		arg.FundID,
		arg.AmountCents,
		arg.NumEnrollments,
		arg.Status,
		arg.Description,
		arg.Notes,
		arg.PayoutDate,
		arg.SenderBatchID,
		arg.ApprovalDeadline,
	)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const insertPayout = `-- name: InsertPayout :one
INSERT INTO payout (id, fund_enrollment_id, batch_id, amount_cents, status, description, notes,
                    payout_date, destination_email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, fund_enrollment_id, batch_id, amount_cents, status, failure_reason, notes, description, payout_date, created, updated, provider_payout_item_id, destination_email, provider_fee_cents
`

type InsertPayoutParams struct {
	ID               uuid.UUID
	FundEnrollmentID uuid.UUID
	BatchID          uuid.UUID
	AmountCents      int32
	Status           PayoutStatus
	Description      pgtype.Text
	Notes            pgtype.Text
	PayoutDate       pgtype.Timestamptz
	DestinationEmail string
}

func (q *Queries) InsertPayout(ctx context.Context, arg InsertPayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, insertPayout,
		arg.ID,
		arg.FundEnrollmentID,
		arg.BatchID,
		arg.AmountCents,
		arg.Status,
		arg.Description,
		arg.Notes,
		arg.PayoutDate,
		arg.DestinationEmail,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.FundEnrollmentID,
		&i.BatchID,
		&i.AmountCents,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.ProviderPayoutItemID,
		&i.DestinationEmail,
		&i.ProviderFeeCents,
	)
	return i, err
}

const isFundActive = `-- name: IsFundActive :one
SELECT active
FROM fund
WHERE id = $1
`

// Lets the service say "that fund is closed" rather than "nobody is eligible",
// which are very different things to read on a payout you expected to run.
func (q *Queries) IsFundActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isFundActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const markBatchPayoutReminderSent = `-- name: MarkBatchPayoutReminderSent :one
UPDATE batch_payout
SET reminder_sent_at = now(),
    updated          = now()
WHERE id = $1
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

func (q *Queries) MarkBatchPayoutReminderSent(ctx context.Context, id uuid.UUID) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, markBatchPayoutReminderSent, id)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const rejectBatchPayout = `-- name: RejectBatchPayout :one
UPDATE batch_payout
SET status         = 'cancelled',
    failure_reason = $2,
    updated        = now()
WHERE id = $1
  AND status = 'awaiting_approval'
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

type RejectBatchPayoutParams struct {
	ID            uuid.UUID
	FailureReason pgtype.Text
}

func (q *Queries) RejectBatchPayout(ctx context.Context, arg RejectBatchPayoutParams) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, rejectBatchPayout, arg.ID, arg.FailureReason)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const setBatchPayoutStatus = `-- name: SetBatchPayoutStatus :one
UPDATE batch_payout
SET status         = $2,
    failure_reason = $3,
    updated        = now()
WHERE id = $1
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

type SetBatchPayoutStatusParams struct {
	ID            uuid.UUID
	Status        PayoutStatus
	FailureReason pgtype.Text
}

func (q *Queries) SetBatchPayoutStatus(ctx context.Context, arg SetBatchPayoutStatusParams) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, setBatchPayoutStatus, arg.ID, arg.Status, arg.FailureReason)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const setBatchPayoutSubmitted = `-- name: SetBatchPayoutSubmitted :one
UPDATE batch_payout
SET provider_batch_id = $2,
    status            = 'pending',
    updated           = now()
WHERE id = $1
  AND status = 'ready'
RETURNING id, fund_id, amount_cents, num_enrollments, status, failure_reason, notes, description, provider_batch_id, payout_date, created, updated, sender_batch_id, approval_deadline, approved_by, approved_at, reminder_sent_at
`

type SetBatchPayoutSubmittedParams struct {
	ID              uuid.UUID
	ProviderBatchID pgtype.Text
}

// Records the provider's batch ID and moves the batch to 'pending'. Constrained to
// 'ready' so a submission can only ever happen once per approved batch.
func (q *Queries) SetBatchPayoutSubmitted(ctx context.Context, arg SetBatchPayoutSubmittedParams) (BatchPayout, error) {
	row := q.db.QueryRow(ctx, setBatchPayoutSubmitted, arg.ID, arg.ProviderBatchID)
	var i BatchPayout
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AmountCents,
		&i.NumEnrollments,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.ProviderBatchID,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.SenderBatchID,
		&i.ApprovalDeadline,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const setPayoutProviderItemId = `-- name: SetPayoutProviderItemId :one
UPDATE payout
SET provider_payout_item_id = $2,
    updated                 = now()
WHERE id = $1
RETURNING id, fund_enrollment_id, batch_id, amount_cents, status, failure_reason, notes, description, payout_date, created, updated, provider_payout_item_id, destination_email, provider_fee_cents
`

type SetPayoutProviderItemIdParams struct {
	ID                   uuid.UUID
	ProviderPayoutItemID pgtype.Text
}

func (q *Queries) SetPayoutProviderItemId(ctx context.Context, arg SetPayoutProviderItemIdParams) (Payout, error) {
	row := q.db.QueryRow(ctx, setPayoutProviderItemId, arg.ID, arg.ProviderPayoutItemID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.FundEnrollmentID,
		&i.BatchID,
		&i.AmountCents,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.ProviderPayoutItemID,
		&i.DestinationEmail,
		&i.ProviderFeeCents,
	)
	return i, err
}

const setPayoutResultById = `-- name: SetPayoutResultById :one
UPDATE payout
SET provider_payout_item_id = $2,
    status                  = $3,
    failure_reason          = $4,
    provider_fee_cents      = $5,
    updated                 = now()
WHERE id = $1
RETURNING id, fund_enrollment_id, batch_id, amount_cents, status, failure_reason, notes, description, payout_date, created, updated, provider_payout_item_id, destination_email, provider_fee_cents
`

type SetPayoutResultByIdParams struct {
	ID                   uuid.UUID
	ProviderPayoutItemID pgtype.Text
	Status               PayoutStatus
	FailureReason        pgtype.Text
	ProviderFeeCents     int32
}

// Reconciliation writes back by our own payout ID, recovered from the sender_item_id
// echoed by the provider. The provider's item ID is only ever learned here -- the
// create-batch response returns none -- so it is recorded in the same statement as
// the status it belongs to.
func (q *Queries) SetPayoutResultById(ctx context.Context, arg SetPayoutResultByIdParams) (Payout, error) {
	row := q.db.QueryRow(ctx, setPayoutResultById,
		arg.ID,
		arg.ProviderPayoutItemID,
		arg.Status,
		arg.FailureReason,
		arg.ProviderFeeCents,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.FundEnrollmentID,
		&i.BatchID,
		&i.AmountCents,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.ProviderPayoutItemID,
		&i.DestinationEmail,
		&i.ProviderFeeCents,
	)
	return i, err
}

const setPayoutStatusByProviderItemId = `-- name: SetPayoutStatusByProviderItemId :one
UPDATE payout
SET status           = $2,
    failure_reason   = $3,
    provider_fee_cents = $4,
    updated          = now()
WHERE provider_payout_item_id = $1
RETURNING id, fund_enrollment_id, batch_id, amount_cents, status, failure_reason, notes, description, payout_date, created, updated, provider_payout_item_id, destination_email, provider_fee_cents
`

type SetPayoutStatusByProviderItemIdParams struct {
	ProviderPayoutItemID pgtype.Text
	Status               PayoutStatus
	FailureReason        pgtype.Text
	ProviderFeeCents     int32
}

// Driven by per-item provider webhooks, which key on the item ID rather than ours.
func (q *Queries) SetPayoutStatusByProviderItemId(ctx context.Context, arg SetPayoutStatusByProviderItemIdParams) (Payout, error) {
	row := q.db.QueryRow(ctx, setPayoutStatusByProviderItemId,
		arg.ProviderPayoutItemID,
		arg.Status,
		arg.FailureReason,
		arg.ProviderFeeCents,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.FundEnrollmentID,
		&i.BatchID,
		&i.AmountCents,
		&i.Status,
		&i.FailureReason,
		&i.Notes,
		&i.Description,
		&i.PayoutDate,
		&i.Created,
		&i.Updated,
		&i.ProviderPayoutItemID,
		&i.DestinationEmail,
		&i.ProviderFeeCents,
	)
	return i, err
}
