// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :many
INSERT INTO webhook_delivery (transmission_id, event_type)
VALUES ($1, $2)
ON CONFLICT (transmission_id) DO NOTHING
RETURNING transmission_id, event_type, received_at
`

type RecordWebhookDeliveryParams struct {
	TransmissionID string
	EventType      string
}

// Records that a webhook has been accepted, and reports whether it is new.
//
// DO NOTHING rather than an error: a replay is a thing to ignore, not a fault.
// No rows returned means we have seen this transmission before.
func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, recordWebhookDelivery, arg.TransmissionID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(&i.TransmissionID, &i.EventType, &i.ReceivedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
